- hosts: app-server
  tasks:
    - name: add ppa repository for openjdk
      apt_repository:
        repo: ppa:openjdk-r/ppa

    - name: install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - openjdk-11-jre-headless
          - unzip
    - name: create folder for demo
      file:
        name: /opt/demo
        state: directory
    - name: unarchive demo
      copy:
        src: ../target/spring-boot-example-0.0.1-SNAPSHOT.jar
        dest: /opt/demo
    - name: create service demo
      copy:
        src: files/demo.service
        dest: /etc/systemd/system/demo.service
    - name: service demo start
      service:
        name: demo
        state: restarted
        enabled: yes
        daemon_reload: yes